<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Asset_article extends Model
{

     protected $table = 'asset_article';
     protected $primaryKey = 'ARTICLE_ID';
     protected $fillable = [
          'ARTICLE_ID',
          'ARTICLE_NUM',
          'ARTICLE_NUM_OLD',
          'NUM1',
          'NUM2',
          'NUM3',
          'NUM4',
          'ARTICLE_NAME',
          'ARTICLE_NAME_EN',
          'MODEL_ID',
          'SIZE_ID',
          'DEVICE_NUM',
          'SERIAL_NO',
          'SUPPLIER_ID',
          'SALE_ID',
          'COUNTRY_ID',
          'TYPE_ID',
          'TYPE_SUB_ID',
          'BRAND_ID',
          'SECTION_ID',
          'COLOR_ID',
          'RECEIVE_DATE',
          'PRICE_PER_UNIT',
          'TYPE_MONEY_ID',
          'TYPE_MONEY_COMMENT',
          'METHOD_ID',
          'DOC_NO_NUM',
          'DOC_NO_FILE',
          'REMARK','DEPT',
          'UNIT_ID',
          'EXPIRED',
          'DEPREC',
          'NOTES',
          'LOCATEDIVISION',
          'LOCATEDEPT',
          'LOCATESECTION',
          'WAY_NAME',
          'CHANGE',
          'SALER',
          'STATUS_ID',
          'DEPARTMENT_SUB_ID',
          'PERSON_ID',
          'IMAGES',
          'EXPIRE_DOC',
          'EXPIRE_DATE',
          'EXPIRE_DATE_SUBMIT',
          'DATE_DOC',
          'CAR_TYPE_ID',
          'CAR_REG',
          'UPDATE_PERSON_ID',
          'UPDATE_DATE_TIME',
          'ARTICLE_MODELS',
          'MODEL_REGIS',
          'GROUP_ID',
          'CLASS_ID',
          'PROPOTIES_ID',
          'ROOM_ID',
          'LEVEL_ID',
          'OLD_USE',
          'VENDOR_ID',
          'DEP_ID',
          'LOCATION_ID',
          'IMG',
          'BUY_ID',
          'LOCATION_LEVEL_ID',
          'LEVEL_ROOM_ID',
          'AR_REGIS_ID',
          'YEAR_ID',
          'OPENS',
          'DECLINE_ID',
          'CODE_REF',
          'BUDGET_ID',
          'ARTICLE_PROP',
          'SUP_FSN',
          'SUP_ID',
          'AR_REGIS_COUNT',
          'TYPE_VALUE_ID',
          'QRCODE',
          'PM_TYPE_ID',
          'CAL_TYPE_ID',
          'RISK_TYPE_ID',
          'DEP_SUB_SUB_ID',
          'DEP_SUB_SUB_NAME',        
         
     ];
}
